[libraries]

lib.files = [
"thrash/isa_pkg.vhd",
"thrash/EX_Overview.vhd",
"projekt-mikrorechner/thrash/isa_pkg.vhd",
"projekt-mikrorechner/thrash/EX_Overview.vhd",
"mrProject/mr_project/reg.vhd",
"mrProject/mr_project/1_Instruction_Fetch/instF_tb.vhd",
"mrProject/mr_project/1_Instruction_Fetch/instF.vhd",
"mrProject/mr_project/5_Write_Back/WB.vhd",
"mrProject/mr_project/ram_tb.vhd",
"mrProject/mr_project/5_Write_Back/WBTest.vhd",
"mrProject/mr_project/2_Instruction_Decode/opcodes.vhd",
"mrProject/mr_project/3_Execution/aluTest.vhd",
"mrProject/mr_project/3_Execution/EX.vhd",
"mrProject/mr_project/3_Execution/alu_opcode.vhd",
"mrProject/mr_project/2_Instruction_Decode/registerbank_tb.vhd",
"mrProject/mr_project/2_Instruction_Decode/registerbank.vhd",
"mrProject/mr_project/3_Execution/EXTest.vhd",
"mrProject/mr_project/2_Instruction_Decode/funct_codes.vhd",
"mrProject/mr_project/3_Execution/alu.vhd",
"mrProject/mr_project/2_Instruction_Decode/IDTest.vhd",
"mrProject/mr_project/2_Instruction_Decode/ID.vhd",
"projekt-mikrorechner/thrash/introVHDL/delayLine/delayLine.vhd",
"projekt-mikrorechner/thrash/introVHDL/delayLine/reg.vhd",
"projekt-mikrorechner/thrash/introVHDL/delayLine/dlTest.vhd",
"projekt-mikrorechner/thrash/introVHDL/fsm-examples/mealy.vhd",
"projekt-mikrorechner/thrash/introVHDL/fsm-examples/moore.vhd",
"mrProject/mr_project/work/memorySim/rom.vhd",
"mrProject/mr_project/work/memorySim/memPkg.vhd",
"mrProject/mr_project/work/memorySim/procTest.vhd",
"mrProject/mr_project/work/memorySim/ramB.vhd",
"mrProject/mr_project/work/memorySim/ramIO.vhd",
"mrProject/mr_project/4_Memory_Access/MEM.vhd",
"projekt-mikrorechner/thrash/introVHDL/trafficLight/tlcWalk1.vhd",
"projekt-mikrorechner/thrash/introVHDL/trafficLight/tlcWalk.vhd",
"projekt-mikrorechner/thrash/introVHDL/trafficLight/tlcTest.vhd",
"projekt-mikrorechner/thrash/introVHDL/trafficLight/tlcDiff.vhd",
"mrProject/mr_project/4_Memory_Access/MEMTest.vhd",
"mrProject/mr_project/Prozessor.vhd",
"mrProject/memorySim/rom.vhd",
"mrProject/memorySim/memPkg.vhd",
"mrProject/memorySim/procTest.vhd",
"mrProject/memorySim/ramB.vhd",
"mrProject/memorySim/ramIO.vhd",
"thrash/introVHDL/fsm-examples/mealy.vhd",
"thrash/introVHDL/fsm-examples/moore.vhd",
"thrash/introVHDL/delayLine/delayLine.vhd",
"thrash/introVHDL/trafficLight/tlcDiff.vhd",
"thrash/introVHDL/delayLine/reg.vhd",
"thrash/introVHDL/delayLine/dlTest.vhd",
"projekt-mikrorechner/mrProject/mr_project/Prozessor.vhd",
"projekt-mikrorechner/mrProject/mr_project/4_Memory_Access/MEMTest.vhd",
"projekt-mikrorechner/mrProject/mr_project/4_Memory_Access/MEM.vhd",
"projekt-mikrorechner/mrProject/mr_project/5_Write_Back/WBTest.vhd",
"projekt-mikrorechner/mrProject/mr_project/5_Write_Back/WB.vhd",
"projekt-mikrorechner/mrProject/mr_project/2_Instruction_Decode/opcodes.vhd",
"projekt-mikrorechner/mrProject/mr_project/2_Instruction_Decode/registerbank_tb.vhd",
"projekt-mikrorechner/mrProject/mr_project/2_Instruction_Decode/registerbank.vhd",
"projekt-mikrorechner/mrProject/mr_project/2_Instruction_Decode/funct_codes.vhd",
"projekt-mikrorechner/mrProject/mr_project/2_Instruction_Decode/IDTest.vhd",
"projekt-mikrorechner/mrProject/mr_project/2_Instruction_Decode/ID.vhd",
"projekt-mikrorechner/mrProject/mr_project/1_Instruction_Fetch/instF_tb.vhd",
"projekt-mikrorechner/mrProject/mr_project/1_Instruction_Fetch/instF.vhd",
"projekt-mikrorechner/mrProject/mr_project/work/memorySim/ramB.vhd",
"projekt-mikrorechner/mrProject/mr_project/work/memorySim/ramIO.vhd",
"projekt-mikrorechner/mrProject/mr_project/work/memorySim/procTest.vhd",
"projekt-mikrorechner/mrProject/mr_project/work/memorySim/rom.vhd",
"projekt-mikrorechner/mrProject/mr_project/work/memorySim/memPkg.vhd",
"projekt-mikrorechner/mrProject/mr_project/ram_tb.vhd",
"projekt-mikrorechner/mrProject/mr_project/reg.vhd",
"projekt-mikrorechner/mrProject/mr_project/3_Execution/EX.vhd",
"projekt-mikrorechner/mrProject/mr_project/3_Execution/alu_opcode.vhd",
"projekt-mikrorechner/mrProject/mr_project/3_Execution/EXTest.vhd",
"projekt-mikrorechner/mrProject/mr_project/3_Execution/alu.vhd",
"projekt-mikrorechner/mrProject/mr_project/3_Execution/aluTest.vhd",
"thrash/introVHDL/trafficLight/tlcTest.vhd",
"thrash/introVHDL/trafficLight/tlcWalk1.vhd",
"thrash/introVHDL/trafficLight/tlcWalk.vhd",
"projekt-mikrorechner/mrProject/memorySim/rom.vhd",
"projekt-mikrorechner/mrProject/memorySim/memPkg.vhd",
"projekt-mikrorechner/mrProject/memorySim/procTest.vhd",
"projekt-mikrorechner/mrProject/memorySim/ramB.vhd",
"projekt-mikrorechner/mrProject/memorySim/ramIO.vhd",
]
